import { GoogleGenAI, Modality } from "@google/genai";

const getGenerativePart = async (imageSource: File | string) => {
  const getBase64 = (source: File | string): Promise<{ data: string; mimeType: string }> => {
    return new Promise((resolve, reject) => {
      if (source instanceof File) {
        const reader = new FileReader();
        reader.onloadend = () => {
          if (typeof reader.result === 'string') {
            const [header, data] = reader.result.split(',');
            const mimeType = header.match(/:(.*?);/)?.[1] || source.type;
            resolve({ data, mimeType });
          } else {
            reject(new Error("Failed to read file as data URL"));
          }
        };
        reader.onerror = (error) => reject(error);
        reader.readAsDataURL(source);
      } else if (typeof source === 'string') {
        const [header, data] = source.split(',');
        const mimeType = header.match(/:(.*?);/)?.[1] || 'image/png';
        resolve({ data, mimeType });
      } else {
        reject(new Error("Unsupported image source type"));
      }
    });
  };

  const { data, mimeType } = await getBase64(imageSource);

  return {
    inlineData: {
      data,
      mimeType,
    },
  };
};

export const editImageWithGemini = async (imageSource: File | string, prompt: string): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const imagePart = await getGenerativePart(imageSource);

    const textPart = {
      text: prompt,
    };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [imagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error) {
    if (error instanceof Error && (error.message.includes("API Key must be set") || error.message.includes("API key not valid"))) {
      throw new Error("A configured API Key is required, but was not found. Please ensure the API Key is correctly set in the deployment environment's secrets.");
    }
    throw error;
  }
};